---
- name: Elastiflow
  hosts: localhost

  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: latest
        install_recommends: no

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add specified repository into sources list using specified filename
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic
        update_cache: yes

    - name: Install Elastic stack
      apt:
        name: '{{ item.name }}={{ item.version }}'
        state: present
      with_items:
        - { name: 'elasticsearch', version: '7.13.1' }
        - { name: 'kibana', version: '7.13.1' }
        - { name: 'logstash', version: '1:7.13.1-1' }

    - name: Logstash plugin
      command: '{{ item }}'
      with_items:
        - /usr/share/logstash/bin/logstash-plugin install logstash-codec-sflow
        - /usr/share/logstash/bin/logstash-plugin update logstash-codec-netflow
        - /usr/share/logstash/bin/logstash-plugin update logstash-input-udp
        - /usr/share/logstash/bin/logstash-plugin update logstash-input-tcp
        - /usr/share/logstash/bin/logstash-plugin update logstash-filter-dns
        - /usr/share/logstash/bin/logstash-plugin update logstash-filter-geoip
        - /usr/share/logstash/bin/logstash-plugin update logstash-filter-translate
